version: "3.3"

services:
  alma-inventory:
    image: cedelis/alma-inventory-node:0.9
    ports:
      - 80:80
    volumes:
      - .:/usr/src/app/temp
      - "./local.prop.orgs:/var/data/local.prop.orgs"
      - "./gsheet.prop.json:/usr/src/app/gsheet.prop.json"
      - "./webapp/index.html:/usr/src/app/index.html"
      - "./webapp/barcode.js:/usr/src/app/barcode.js"
    tty: true
    stdin_open: true
